services:
  db:
    image: postgres:15-alpine
    container_name: bookstore_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookstore_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: bookstore_api_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password123@db:5432/bookstore_db
      - SECRET_KEY=super-secret-key-change-in-production
    depends_on:
      - db

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

volumes:
  postgres_data:
